[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"
rustflags = ["--cfg=web_sys_unstable_apis"]

[env]
WASM_SERVER_RUNNER_ADDRESS = "0.0.0.0"
WASM_SERVER_RUNNER_HTTPS = "true"

[build]
target = "wasm32-unknown-unknown"
